version: '3'

services:
  mysql:
    image: mysql:5.7
    container_name: crm-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: crm
      MYSQL_PASSWORD: root
    ports:
      - 3306:3306
    volumes:
      - .data/mysql:/var/lib/mysql