// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"database/sql"
	"github.com/google/wire"
	"github.com/paulojr83/crm-backend/internal/entity"
	"github.com/paulojr83/crm-backend/internal/infra/database"
	"github.com/paulojr83/crm-backend/internal/infra/web"
)

import (
	_ "github.com/go-sql-driver/mysql"
)

// Injectors from wire.go:

func NewWebCustomerHandler(db *sql.DB) *web.WebCustomerHandler {
	customerRepository := database.NewCustomerRepository(db)
	webCustomerHandler := web.NewWebCustomerHandler(customerRepository)
	return webCustomerHandler
}

// wire.go:

var setCustomerRepositoryDependency = wire.NewSet(database.NewCustomerRepository, wire.Bind(new(entity.CustomerRepositoryInterface), new(*database.CustomerRepository)))
